class Common {
  static const String guideEmbedding = 
      'Halaman Embedding berfungsi untuk menyisipkan Hidden Image ke dalam sebuah Host Image. Proses ini membutuhkan tiga komponen, yaitu host Image, hidden Image dan kunci. Key atau kunci merupakan kombinasi angka dari 1-1023 yang berguna untuk mengamankan citra rahasia. Aplikasi akan memproses ketiga data masukan tersebut menjadi sebuah citra stego dalam format BW (Black and White). Fitur Attack berfungsi untuk menguji ketahanan dari hidden image yang akan disisipkan. Dalam pemrosesan steganografi citra, Kuantum Spread Spectrum memiliki waktu pemrosesan paling singkat dibandingkan Kuantum DCT dan Kuantum Wavelet. Namun, Kuantum DCT dan Kuantum Wavelet memiliki ketahanan lebih baik saat di-Attack dibandingkan Kuantum Spread Spectrum.';
  static const String steganographyContent =
      'Steganografi adalah Seni dan Ilmu menyembunyikan pesan ke dalam sebuah media dengan suatu cara sehingga selain pengirim dan penerima atau pihak yang mengerti, tidak ada seorang pun yang mengetahui atau menyadari bahwa sebenarnya ada suatu pesan rahasia.';
  static const String Quantum = 
      'Teknologi quantum adalah bidang ilmu yang memanfaatkan prinsip-prinsip mekanika kuantum untuk mengembangkan sistem, perangkat, dan aplikasi yang berbeda dari teknologi konvensional. Mekanika kuantum adalah teori fisika yang menjelaskan perilaku partikel-partikel kecil, seperti atom dan partikel subatomik, yang berbeda secara signifikan dengan hukum fisika klasik yang berlaku pada skala makroskopik.';
  static const String guideExraction = 
      'Halaman Extraction berfungsi untuk mengekstraksi citra stego yang dihasilkan dari halaman Embedding. Proses ini membutuhkan 2 komponen, yaitu file.mat dan kunci. File.mat merupakan sebuah file yang berisi matriks citra stego dalam kuantum. Kunci atau key merupakan kombinasi angka dari 1-1023 yang sama dengan kunci yang terdapat pada file.mat yang diinputkan. Aplikasi akan memproses kedua data tersebut menjadi sebuah hidden image. Dalam pemrosesan ekstraksi steganografi citra, Kuantum Spread Spectrum memiliki waktu pemrosesan paling singkat dibandingkan Kuantum DCT dan Kuantum Wavelet. Namun, Kuantum DCT dan Kuantum Wavelet memiliki kualitas ekstraksi citra yang lebih baik dibandingkan Kuantum Spread Sprektrum.';  
}
